### PR TITLE
Update the version filter to accept the new 2.x version line

### PR DESCRIPTION
**Pull request by ForestEckhardt**
This version line help to resolve an issue that I was having with watchexec running on the Static Stack.

https://github.com/watchexec/watchexec/issues/814

### CODE REVIEW

**Comment by dmikusa** [comment]
My usual question with major version bumps is do we need to keep supporting the previous major version. I don't know what's changed between the version we're bundling and the latest major, but it's been a while since we updated. We should probably do some quick tests with the use cases we support and the new major version to see if anything breaks.

It's easier to just migrate major versions and for tools like this, we're not usually installing them for the user but for features in the buildpacks so I feel like we can justify changing the version and dropping the old version at the same time. Thoughts on that?

**Comment by ForestEckhardt** [comment]
From what I could gather from the release notes this is mostly to get over the first breaking change hump as well as cleaning up a long list of things that have been deprecated for a while. I don't see anything that has been deprecated that we are currently leveraging. I personally don't think that there will be any issue with releasing this new version but it is something that we may need to keep a closer eye on as it sounds like the rate of major releases may be increasing.

**Comment by dmikusa** [comment]
Ok, it sounds like we should probably jump to 2.x and if someone needs to hang back on 1.x, they can do that by pinning the version of the Watchexec buildpack. It'll be a major version jump for the buildpack, so that should help people recognize there's a change.

To update, we need to:

1. Update buildpack toml with the new metadata: https://github.com/paketo-buildpacks/watchexec/blob/main/buildpack.toml#L35-L64
2. Update `.github/pipeline-descriptor.yml` with the new version tag filter. https://github.com/paketo-buildpacks/watchexec/blob/main/.github/pipeline-descriptor.yml#L22-L43

You don't need to worry about the individual workflow files. The Update Pipeline job will regenerate those based on the info in 1.) and 2.).

**Comment by ForestEckhardt** [comment]
> 1. Update buildpack toml with the new metadata: https://github.com/paketo-buildpacks/watchexec/blob/main/buildpack.toml#L35-L64

I was hoping to have this done automatically by the automation. Would it be acceptable to just make the change to the pipeline descriptor?

**Comment by dmikusa** [comment]
I don't think so, but I've not tried it. I think you're going to minimally need to update the versions & URLs. The sha hashes don't need to be correct, but they need to be something. I'll sometimes put the literal string `bad` for the hashes. The update workflow will submit a PR to correct those later. Things do go more smoothly with the hashes though, as the PR tests will fail if they are incorrect.

**Comment by ForestEckhardt** [comment]
Closing in favor of this PR https://github.com/paketo-buildpacks/watchexec/pull/194

**Pull request closed without merging**
